# <font color='blue'>Data Science Academy</font>
# <font color='blue'>Matemática Para Machine Learning</font>

## Lista de Exercícios  - Capítulo 4

O objetivo desta lista de exercícios é você praticar os principais conceitos estudados neste capítulo, ao mesmo tempo que desenvolve suas habilidades em lógica de programação com a linguagem Python. 

Caso tenha dúvidas, isso é absolutamente normal e faça um trabalho de pesquisa a fim de relembrar o formato das operações matemáticas.

Quando encontrar o formato de uma operação que resolva o exercício proposto, use a linguagem Python para representar esta operação. Em essência, é assim que aplicamos Matemática Para Machine Learning, construindo algoritmos e representando esses algoritmos em linguagem de programação.

A maioria das pessoas considera a Matemática e a Física, assustadoras bestas das quais é melhor manter a distância. Computadores, no entanto, podem nos ajudar a domar a complexidade e a aritmética tediosa das manipulações associadas a esses assuntos. De fato, Matemática e Física são muito mais acessíveis, uma vez que você tem o poder de computadores do seu lado.

Divirta-se!!

### Exercício 1 - Considerando os vetores v [1, 2] e w [2, 1], crie um script Python que faça a soma dos vetores. Não use funções de pacotes prontos, somente a linguagem Python pura e suas funções, se necessário.

Dica: A função zip() pode ajudá-lo.

In [1]:
# Solução

vetor1 = [1, 2]
vetor2 = [2, 1]

if len(vetor1) == len(vetor2):
    vetor3 = []
    for i in range(0,len(vetor1)):
        vetor3.append(vetor1[i] + vetor2[i])
print(vetor3)



[3, 3]


### Exercício 2 - Considerando os vetores v [1, 2] e w [2, 1], crie um script Python que faça a subtração dos vetores. Não use funções de pacotes prontos, somente a linguagem Python pura e suas funções, se necessário.

Dica: A função zip() pode ajudá-lo.

In [4]:
# Solução

vetor1 = [1, 2]
vetor2 = [2, 1]

if len(vetor1) == len(vetor2):
    vetor3 = []
    for i in range(0,len(vetor1)):
        vetor3.append(vetor1[i] - vetor2[i])
print(vetor3)


[-1, 1]


### Exercício 3 - Considerando o escalar e vetor abaixo, crie uma função que receba os 2 como parâmetro e multiplique o vetor pelo escalar. Use apenas Python puro.

Dica: List Comprehension pode ajudá-lo aqui. O curso de Python Fundamentos oferece exemplos deste recurso.

In [7]:
# Solução

def SumEscalarInList(escalar, list):
    newList = [item*escalar for item in list]
    print(newList)


num = 3
vetor = [1, 2, 3]
SumEscalarInList(num,vetor)


[3, 6, 9]


### Exercício 4 - Considerando os 2 vetores abaixo, crie uma função Python que faça o dot product entre os 2 vetores e retorne apenas um valor escalar.

In [3]:
# Solução

vetor1 = [1, 2]
vetor2 = [2, 1]
if len(vetor1) == len(vetor2):
    vetor3 = []
    dotPr = 0
    for i in range(0,len(vetor1)):
        vetor3.append(vetor1[i] * vetor2[i])
        dotPr += vetor3[i]
print(vetor3)
print(dotPr)



[2, 2]
4


### Exercício 5 - Resolva o exercício anterior usando a função dot() do NumPy

In [4]:
# Solução

import numpy as np

vetor1 = [1, 2]
vetor2 = [2, 1]

dotPr = np.dot(vetor1,vetor2)
print(dotPr)

4


### Exercício 6 - Crie uma lista em Python com 3 dimensões, preenchida com zeros.

Dica: a função pprint do pacote pprint permite imprimir uma lista tridimensional de forma mais legível.

In [13]:
# Solução

import pprint
lista = [[[1,2,3],[5,7,9],[7,6,3]],[[5,9,8],[6,5,1],[7,2,3]],[[9,7,3],[2,1,3],[9,7,1]]]
pprint.pprint(lista)

[[[1, 2, 3], [5, 7, 9], [7, 6, 3]],
 [[5, 9, 8], [6, 5, 1], [7, 2, 3]],
 [[9, 7, 3], [2, 1, 3], [9, 7, 1]]]


### Exercício 7 - Considerando o vetor criado no item anterior, altere o valor na posição nas coordenadas (2, 1, 0) para 92.

In [14]:
# Solução
import pprint
lista = [[[1,2,3],[5,7,9],[7,6,3]],[[5,9,8],[6,5,1],[7,2,3]],[[9,7,3],[2,1,3],[9,7,1]]]
lista[2][1][0] = 92
pprint.pprint(lista)


[[[1, 2, 3], [5, 7, 9], [7, 6, 3]],
 [[5, 9, 8], [6, 5, 1], [7, 2, 3]],
 [[9, 7, 3], [92, 1, 3], [9, 7, 1]]]


### Exercício 8 - Considere o vetor multidimensional A abaixo. Transforme-o em um vetor de uma única dimensão, com todos os elementos ordenados na mesma sequência do vetor original.

Dica: Esta operação é chamada de flatten do vetor (algo como "achatar" um vetor), sendo uma das operações de pré-processamento mais comum em modelos de Deep Learning para Visão Computacional. NumPy oferece uma função para isso.

In [18]:
# Solução

import numpy as np

A = np.array([[[ 0,  1],
               [ 2,  3],
               [ 4,  5],
               [ 6,  7]],
              [[ 8,  9],
               [10, 11],
               [12, 13],
               [14, 15]],
              [[16, 17],
               [18, 19],
               [20, 21],
               [22, 23]]])

print("\nVetor multidimensional original:\n\n", A)
print(A.flatten())



Vetor multidimensional original:

 [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


### Exercício 9 - Considere o vetor multidimensional A abaixo. Transforme-o em um vetor de uma única dimensão, com todos os elementos ordenados na mesma sequência do vetor original. Use a função ravel() do NumPy.

A função ravel() possui o parâmetro "order" que pode ser "C", "F", "A" ou "K". Qual a diferença entre usar os parâmetros C e F?

In [19]:
# Solução

import numpy as np

A = np.array([[[ 0,  1],
               [ 2,  3],
               [ 4,  5],
               [ 6,  7]],
              [[ 8,  9],
               [10, 11],
               [12, 13],
               [14, 15]],
              [[16, 17],
               [18, 19],
               [20, 21],
               [22, 23]]])

print("\nVetor multidimensional original:\n\n", A)
print(np.ravel(A))
# C ordena por coluna, F ordena por linha



Vetor multidimensional original:

 [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


### Exercício 10 - Calcule o Inner e Outer product dos vetores abaixo.

In [1]:
# Solução

import numpy as np

vetor1 = [1, 2]
vetor2 = [2, 1]

inner = np.dot(vetor1,vetor2)
outer = np.outer(vetor1,vetor2)
print(inner)
print(outer)


4
[[2 1]
 [4 2]]


## Fim